#####################################################################
#  Trigger the Github Action Workflow on a separate repository
#####################################################################
name: 'Trigger the Liquibase Pro CI Workflow'
run-name: Continuous Integration of ${{github.ref}} to ${{github.base_ref}} by ${{ github.actor }}

# This workflow will execute whenever a pull request is opened against
# the 'develop', 'qa', or 'release/'** branch.
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'develop'
      - 'qa'
      - 'release/**'

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    steps:
      - name: Fire event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHA_TRIGGER_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/liquibase/cs-impl-guide-examples/dispatches \
            -d '{"event_type":"dispatch-event"}'
          